# Practical Exercise: Taylor Series

Implement the following steps as best you can:
 1. Write a function to calculate factorials (Yes, there are built-in options. Make your own.)
 2. Write a function to compute a term of a Taylor series of a given degree, at a given point, for a vector of $x$ inputs. It should take another function which calculates the appropriate derivative as an input.
 3. Pick a function to approximate up to at least the 3rd degree. Write functions to compute values of that function, and of at least its first, second, and third derivatives.
 4. Write a function (or functions) which will combine elements from the previous steps to compute Taylor approximations of the 1st, 2nd, and 3rd degree for your chosen function.
 5. Plot your chosen function plus it's 1st, 2nd, and 3rd order approximations for an appropriate range of input values and comment on goodness of fit.

In [39]:
#1. Factorials
def calc_factorial(num):
    if num < 0:
        return("Provide a number > 0")
        
    terms = range(1, num+1)
    res = 1
    for val in terms:
        res = res * val

    return(res)    

calc_factorial(8)

calc_factorial(4)


24

In [85]:
#2. Compute term of taylor series for vector of x inputs
import numpy as np

#Given vector of derivatives, centered at a given point
def calc_taylor(array_of_deriv, center, approx_value):
    #Multiply the vec of derivatives * (approx_value - center)
    diff = approx_value - center
    print(diff)

    #np.array doesn't save as floats, need to save as floats to be able to approximate the difference as terms shrink closer 
    a = np.array(range(len(array_of_deriv))) 
    diff_approx = np.vectorize(float)(a)
    
    for i in diff_approx:
        a = float(diff**i)
        diff_approx[i] = a
        print(a)
    
    factorial_div = np.array(range(1, len(array_of_deriv)+1))
    for i in factorial_div:
        a = calc_factorial(i)
        factorial_div[i-1] = a
        
    terms = array_of_deriv/factorial_div

    #returns each term of the polynomial
    return(np.cumsum(diff*terms))


# Given an array of derivatives, the point you are centering on and the approximation you want to calculate, will find the 
# input_array = np.array([5, 5, 5, 5])
# calc_taylor(input_array, 0, 1)

#3. Pick a function to approximate, compute values of the 1st, 2nd, and 3rd derivatives
# Chose a random 4th degree polynomial, can compare to numerical deriv once we cover
#Approximate $2x^4 + 3x^3 + 2x^2 + x$

def compute_deriv_poly(x):
    base = 2*x**4 + 3*x**3 + 2*x**2 + x
    der1 = 8*x**3 + 9*x**2 + 4*x + 1
    der2 = 24*x**2 + 18*x + 4
    der3 = 48*x + 18
    return(np.array([base, der1, der2, der3]))

# base = $2x^4 + 3x^3 + 2x^2 + x$
# first derivative = 8x^3 + 9x^2 + 4x + 1
# second derivative = 24x^2 + 18x + 4
# third derivative = 48x + 18


#4. combine previous steps to compute taylor approx for first 3 degrees based on input

def taylor_series_approx(center, approx):
    derivs = compute_deriv_poly(center)
    taylor_approx = calc_taylor(derivs, center, approx)

    return(taylor_approx)

#print(taylor_series_approx(1, 1.1))

print(compute_deriv_poly(1))

#t2 = calc_taylor(derivs, 1, 1.1)
#print(t2)
#print(t2[2])

[ 8 22 46 66]


In [26]:
a = np.array([10, 20, 30, 40])

b = np.array(range(1,len(a)+1 ))
print(b)
print(4*a)

print(a/b)

np.sum(4*a)

[1 2 3 4]
[ 40  80 120 160]
[10. 10. 10. 10.]


np.int64(400)

In [52]:

           
compute_deriv_poly(2)

array([ 66, 109, 136, 114])

In [31]:
]

array([1, 2, 3, 4])